#!/usr/bin/env python
from getpass import getpass, getuser
from fabric.api import *
import sys
import os
#@env.gateway = 'username@IPofgatewayHost'

env.user = prompt("Enter ipmon username:  ", default="root")
env.password = getpass('Enter the password: ')

list = []

print(file)
# file function needs to be added before execution any other tasks for multiple host list in file hosts
# how to use this script: fab -f fab_ipmon_dev.py file:name=hosts ipmon_status
def file(**kwargs):
        for key, value in kwargs.iteritems():
                hosts = value
        with open(hosts, "r") as file:
                for line in file:
                        list.append(line)
                env.hosts = list;

def ipmon_restart():
    with settings(warn_only=True):
        run("/etc/init.d/httpd restart")
        run("/etc/init.d/ntpd restart")
        run("/etc/init.d/ipmonstatus stop")
        run("/etc/init.d/IPmonX stop")
        run("/etc/init.d/apache-activemq stop")
        run("/etc/init.d/apache-activemq start")
        run("/etc/init.d/ipmonstatus start")
        run("/etc/init.d/IPmon start")
        run("/etc/init.d/IPmonX start")
        run("/etc/init.d/IPmon-engine-jmx restart")
        run("/etc/init.d/IPreports-client restart")


def ipmon_status():
        sudo('sudo /etc/init.d/IPmon status')

def ipmon_disk():
        #env.user = 'user'
        #env.password = 'password'      
        sudo("find /apps/IPsoft/IPmon/var -type f -not -name '*.gz' -name '*log*' -name '*201*' -exec gzip -9v {} \;")
        sudo("find /apps/IPsoft/IPmon/var -type f -not -name '*.gz' -name '*service-perfdata*201*' -exec gzip -9v {} \;")
        sudo("find /apps/IPsoft/IPmon/engine/jmx/log/jmx1.2/ -type f -not -name '*.gz' -name 'engine.log.201*' -exec gzip -9v {} \;")

		
		fabipmon.py
