---
# Bring stak down

- hosts: loadbalancer
  become: true
  tasks:
    - name: stop the service nginx
      service:
        name: nginx
        state: stopped
    - wait_for: port=80 state=drained

- hosts: webserver
  become: true
  tasks:
    - name: stopped the service apache2
      service:
        name: apache2
        state: stopped
    - wait_for: port=80 state=stopped

- hosts: database
  become: true
  tasks:
    - name: restarted the service mysql
      service:
        name: mysql
        state: restarted
    - wait_for: port=3306 state=started

- hosts: loadbalancer
  become: true
  tasks:
    - name: start the service nginx
      service:
        name: nginx
        state: started
    - wait_for: port=80 state=started
- hosts: webserver
  become: true
  tasks:
    - name: started the service apache2
      service:
        name: apache2
        state: started
    - wait_for: port=80 state=started
