---
- hosts: loadbalancer
  become: true
  tasks:
    - name: ensure nginx is running
      service:
         name: nginx
         state: started

    - name: verify nginx is listening on 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
   - name: ensure apache2 is running
     service:
       name:  apache2
       state: started

   - name: verify apache2 is listening on 80
     wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
   - name: ensure mysql is running
     service:
        name: mysql
        state: started

   - name: verify mysql is listening on 3306
     wait_for: port=3306 timeout=1
- hosts: controler
  tasks:
   - name: verify end-to-end respose load balancer
     uri:
      url: "http://{{item}}"
      return_content: yes
     with_items: "{{ groups.loadbalancer }}"
     register: lb_index

   - name: Check LB Status
     fail:
       msg: "Index failed to return content"
     when: "'Hello, from sunny' not in item.content"
     with_items: "{{lb_index.results}}"


   - name: verify LB to DB end-to-end db respose
     uri:
      url: "http://{{item}}/db"
      return_content: yes
     with_items: "{{ groups.loadbalancer }}"
     register: lb_db

   - name: Check LB to DB Status
     fail:
       msg: "db failed to return content"
     when: "'Database Connected from' not in item.content"
     with_items: "{{lb_db.results}}"
- hosts: loadbalancer
  tasks:
   - name: verify backend LB to APP respose
     uri:
      url: "http://{{item}}"
      return_content: yes
     with_items: "{{ groups.webserver }}"
     register: app_index

   - name: Check LB to APP Status
     fail:
       msg: "Index failed to return content"
     when: "'Hello, from sunny' not in item.content"
     with_items: "{{app_index.results}}"




   - name: verify backend APP to DB respose
     uri:
      url: "http://{{item}}/db"
      return_content: yes
     with_items: "{{ groups.webserver }}"
     register: app_db

   - name: Check APP to DB Status
     fail:
       msg: "db failed to return content"
     when: "'Database Connected from' not in item.content"
     with_items: "{{app_db.results}}"
